server:
  port: 8888
spring:  cloud:    config:      server:
       encrypt:          enabled: false       git:
          uri: https://github.com/yuri-fa/microservice-repo
          search-paths: fornecedor, loja
          default-label: main   